/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SsBackdrop {
    'closeButton': boolean;
    'invisible': boolean;
    'show': boolean;
  }
  interface SsBackdropAttributes extends StencilHTMLAttributes {
    'closeButton'?: boolean;
    'invisible'?: boolean;
    'onClickCloseButton'?: (event: CustomEvent) => void;
    'show'?: boolean;
  }

  interface SsButton {
    'color': 'plain' | 'primary' | 'secondary' | 'danger';
    'type': 'basic' | 'raised' | 'outline' | 'flat';
  }
  interface SsButtonAttributes extends StencilHTMLAttributes {
    'color'?: 'plain' | 'primary' | 'secondary' | 'danger';
    'type'?: 'basic' | 'raised' | 'outline' | 'flat';
  }

  interface SsInput {
    'append': string;
    'errorPattern': string;
    'errorRequired': string;
    'full': boolean;
    'placeholder': string;
    'prepend': string;
    'type': string;
  }
  interface SsInputAttributes extends StencilHTMLAttributes {
    'append'?: string;
    'errorPattern'?: string;
    'errorRequired'?: string;
    'full'?: boolean;
    'onOnChange'?: (event: CustomEvent) => void;
    'onOnInput'?: (event: CustomEvent) => void;
    'onOnKeyDown'?: (event: CustomEvent) => void;
    'onOnKeyUp'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'prepend'?: string;
    'type'?: string;
  }

  interface SsModal {
    'backdrop': boolean;
    'backdropCloseButton': boolean;
    'close': () => void;
    'closeOutside': boolean;
    'open': () => void;
  }
  interface SsModalAttributes extends StencilHTMLAttributes {
    'backdrop'?: boolean;
    'backdropCloseButton'?: boolean;
    'closeOutside'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SsBackdrop': Components.SsBackdrop;
    'SsButton': Components.SsButton;
    'SsInput': Components.SsInput;
    'SsModal': Components.SsModal;
  }

  interface StencilIntrinsicElements {
    'ss-backdrop': Components.SsBackdropAttributes;
    'ss-button': Components.SsButtonAttributes;
    'ss-input': Components.SsInputAttributes;
    'ss-modal': Components.SsModalAttributes;
  }


  interface HTMLSsBackdropElement extends Components.SsBackdrop, HTMLStencilElement {}
  var HTMLSsBackdropElement: {
    prototype: HTMLSsBackdropElement;
    new (): HTMLSsBackdropElement;
  };

  interface HTMLSsButtonElement extends Components.SsButton, HTMLStencilElement {}
  var HTMLSsButtonElement: {
    prototype: HTMLSsButtonElement;
    new (): HTMLSsButtonElement;
  };

  interface HTMLSsInputElement extends Components.SsInput, HTMLStencilElement {}
  var HTMLSsInputElement: {
    prototype: HTMLSsInputElement;
    new (): HTMLSsInputElement;
  };

  interface HTMLSsModalElement extends Components.SsModal, HTMLStencilElement {}
  var HTMLSsModalElement: {
    prototype: HTMLSsModalElement;
    new (): HTMLSsModalElement;
  };

  interface HTMLElementTagNameMap {
    'ss-backdrop': HTMLSsBackdropElement
    'ss-button': HTMLSsButtonElement
    'ss-input': HTMLSsInputElement
    'ss-modal': HTMLSsModalElement
  }

  interface ElementTagNameMap {
    'ss-backdrop': HTMLSsBackdropElement;
    'ss-button': HTMLSsButtonElement;
    'ss-input': HTMLSsInputElement;
    'ss-modal': HTMLSsModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
